services:
  admin:
    image: ${REGISTRY}nocode-builder-admin:${VERSION}
    restart: always
  admin-story:
    image: ${REGISTRY}nocode-builder-admin-story:${VERSION}
    restart: always
  server:
    image: ${REGISTRY}nocode-builder-server:${VERSION}
    restart: always
  postgres:
    image: ${REGISTRY}nocode-builder-postgres:${VERSION}
    restart: always
  nginx:
    image: ${REGISTRY}nocode-builder-nginx:${VERSION}
    restart: always
