services:
  admin:
    build:
      context: .
      dockerfile: ./admin/Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - server
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - postgres
  postgres:
    build:
      context: .
      dockerfile: ./db/postgres/Dockerfile
    volumes:
      - pgdata:/var/lib/postgresql/data       
    ports:
      - "5432:5432"

volumes:
  pgdata: