services:
  admin:
    ports:
      - '3001:80'
    environment:
      - NODE_ENV=production
    depends_on:
      - server
  admin-story:
    ports:
      - '3002:80'
    environment:
      - NODE_ENV=production
    depends_on:
      - server
  server:
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://yarnb:123456a.@postgres:5432/local?schema=public
    depends_on:
      - postgres
  postgres:
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  nginx:
    ports:
      - '80:80'
    depends_on:
      - admin
      - server

volumes:
  pgdata:
