import {
  WidgetCategory,
  WidgetPlatformType,
  WidgetDisplay,
} from '@prisma/client';
import { WidgetData } from 'prisma/types';

export const antdMobileWidgetsData: WidgetData[] = [
  {
    widgetLib: 'antd-mobile',
    name: 'AutoCenter',
    category: WidgetCategory.Layout,
    platforms: [WidgetPlatformType.MobileWeb],
    display: WidgetDisplay.Block,
  },
  {
    widgetLib: 'antd-mobile',
    name: 'SafeArea',
    category: WidgetCategory.Layout,
    platforms: [WidgetPlatformType.MobileWeb],
    display: WidgetDisplay.Block,
  },
  {
    widgetLib: 'antd-mobile',
    name: 'CapsuleTabs',
    category: WidgetCategory.Navigation,
    platforms: [WidgetPlatformType.MobileWeb],
    display: WidgetDisplay.Flex,
  },
  {
    widgetLib: 'antd-mobile',
    name: 'IndexBar',
    category: WidgetCategory.Navigation,
    platforms: [WidgetPlatformType.MobileWeb],
    display: WidgetDisplay.Block,
  },
  {
    widgetLib: 'antd-mobile',
    name: 'JumboTabs',
    category: WidgetCategory.Navigation,
    platforms: [WidgetPlatformType.MobileWeb],
    display: WidgetDisplay.Flex,
  },
  {
    widgetLib: 'antd-mobile',
    name: 'NavBar',
    category: WidgetCategory.Navigation,
    platforms: [WidgetPlatformType.MobileWeb],
    display: WidgetDisplay.Flex,
  },
  {
    widgetLib: 'antd-mobile',
    name: 'SideBar',
    category: WidgetCategory.Navigation,
    platforms: [WidgetPlatformType.MobileWeb],
    display: WidgetDisplay.Block,
  },
  {
    widgetLib: 'antd-mobile',
    name: 'TabBar',
    category: WidgetCategory.Navigation,
    platforms: [WidgetPlatformType.MobileWeb],
    display: WidgetDisplay.Flex,
  },
  {
    widgetLib: 'antd-mobile',
    name: 'Avatar',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.MobileWeb],
    display: WidgetDisplay.InlineBlock,
  },
  {
    widgetLib: 'antd-mobile',
    name: 'Card',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.MobileWeb],
    display: WidgetDisplay.Block,
  },
  {
    widgetLib: 'antd-mobile',
    name: 'Collapse',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.MobileWeb],
    display: WidgetDisplay.Block,
  },
  {
    widgetLib: 'antd-mobile',
    name: 'Ellipsis',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.MobileWeb],
    display: WidgetDisplay.InlineBlock,
  },
  {
    widgetLib: 'antd-mobile',
    name: 'FloatingPanel',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.MobileWeb],
    display: WidgetDisplay.Block,
  },
  {
    widgetLib: 'antd-mobile',
    name: 'Image',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.MobileWeb],
    display: WidgetDisplay.InlineBlock,
  },
  {
    widgetLib: 'antd-mobile',
    name: 'ImageViewer',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.MobileWeb],
    display: WidgetDisplay.Block,
  },
  {
    widgetLib: 'antd-mobile',
    name: 'InfiniteScroll',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.MobileWeb],
    display: WidgetDisplay.Block,
  },
  {
    widgetLib: 'antd-mobile',
    name: 'List',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.MobileWeb],
    display: WidgetDisplay.Block,
  },
  {
    widgetLib: 'antd-mobile',
    name: 'PageIndicator',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.MobileWeb],
    display: WidgetDisplay.Block,
  },
  {
    widgetLib: 'antd-mobile',
    name: 'Steps',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.MobileWeb],
    display: WidgetDisplay.Block,
  },
  {
    widgetLib: 'antd-mobile',
    name: 'Swiper',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.MobileWeb],
    display: WidgetDisplay.Block,
  },
  {
    widgetLib: 'antd-mobile',
    name: 'Tag',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.MobileWeb],
    display: WidgetDisplay.InlineBlock,
  },
  {
    widgetLib: 'antd-mobile',
    name: 'WaterMark',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.MobileWeb],
    display: WidgetDisplay.Block,
  },
  {
    widgetLib: 'antd-mobile',
    name: 'Footer',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.MobileWeb],
    display: WidgetDisplay.Block,
  },
  {
    widgetLib: 'antd-mobile',
    name: 'Cascader',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.MobileWeb],
    display: WidgetDisplay.Block,
  },
  {
    widgetLib: 'antd-mobile',
    name: 'CascaderView',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.MobileWeb],
    display: WidgetDisplay.Block,
  },
  {
    widgetLib: 'antd-mobile',
    name: 'CheckList',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.MobileWeb],
    display: WidgetDisplay.Block,
  },
  {
    widgetLib: 'antd-mobile',
    name: 'Checkbox',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.MobileWeb],
    display: WidgetDisplay.InlineBlock,
  },
  {
    widgetLib: 'antd-mobile',
    name: 'Form',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.MobileWeb],
    display: WidgetDisplay.Block,
  },
  {
    widgetLib: 'antd-mobile',
    name: 'Input',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.MobileWeb],
    display: WidgetDisplay.InlineBlock,
  },
  {
    widgetLib: 'antd-mobile',
    name: 'Picker',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.MobileWeb],
    display: WidgetDisplay.Block,
  },
  {
    widgetLib: 'antd-mobile',
    name: 'PickerView',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.MobileWeb],
    display: WidgetDisplay.Block,
  },
  {
    widgetLib: 'antd-mobile',
    name: 'Radio',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.MobileWeb],
    display: WidgetDisplay.InlineBlock,
  },
  {
    widgetLib: 'antd-mobile',
    name: 'Rate',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.MobileWeb],
    display: WidgetDisplay.InlineBlock,
  },
  {
    widgetLib: 'antd-mobile',
    name: 'SearchBar',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.MobileWeb],
    display: WidgetDisplay.Block,
  },
  {
    widgetLib: 'antd-mobile',
    name: 'Selector',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.MobileWeb],
    display: WidgetDisplay.Block,
  },
  {
    widgetLib: 'antd-mobile',
    name: 'Slider',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.MobileWeb],
    display: WidgetDisplay.Block,
  },
  {
    widgetLib: 'antd-mobile',
    name: 'Stepper',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.MobileWeb],
    display: WidgetDisplay.Block,
  },
  {
    widgetLib: 'antd-mobile',
    name: 'Switch',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.MobileWeb],
    display: WidgetDisplay.InlineBlock,
  },
  {
    widgetLib: 'antd-mobile',
    name: 'TextArea',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.MobileWeb],
    display: WidgetDisplay.Block,
  },
  {
    widgetLib: 'antd-mobile',
    name: 'ActionSheet',
    category: WidgetCategory.Feedback,
    platforms: [WidgetPlatformType.MobileWeb],
    display: WidgetDisplay.Block,
  },
  {
    widgetLib: 'antd-mobile',
    name: 'Dialog',
    category: WidgetCategory.Feedback,
    platforms: [WidgetPlatformType.MobileWeb],
    display: WidgetDisplay.Block,
  },
  {
    widgetLib: 'antd-mobile',
    name: 'Empty',
    category: WidgetCategory.Feedback,
    platforms: [WidgetPlatformType.MobileWeb],
    display: WidgetDisplay.Block,
  },
  {
    widgetLib: 'antd-mobile',
    name: 'ErrorBlock',
    category: WidgetCategory.Feedback,
    platforms: [WidgetPlatformType.MobileWeb],
    display: WidgetDisplay.Block,
  },
  {
    widgetLib: 'antd-mobile',
    name: 'Loading',
    category: WidgetCategory.Feedback,
    platforms: [WidgetPlatformType.MobileWeb],
    display: WidgetDisplay.Block,
  },
  {
    widgetLib: 'antd-mobile',
    name: 'Mask',
    category: WidgetCategory.Feedback,
    platforms: [WidgetPlatformType.MobileWeb],
    display: WidgetDisplay.Block,
  },
  {
    widgetLib: 'antd-mobile',
    name: 'Modal',
    category: WidgetCategory.Feedback,
    platforms: [WidgetPlatformType.MobileWeb],
    display: WidgetDisplay.Block,
  },
  {
    widgetLib: 'antd-mobile',
    name: 'Popover',
    category: WidgetCategory.Feedback,
    platforms: [WidgetPlatformType.MobileWeb],
    display: WidgetDisplay.Block,
  },
  {
    widgetLib: 'antd-mobile',
    name: 'Popup',
    category: WidgetCategory.Feedback,
    platforms: [WidgetPlatformType.MobileWeb],
    display: WidgetDisplay.Block,
  },
  {
    widgetLib: 'antd-mobile',
    name: 'ProgressBar',
    category: WidgetCategory.Feedback,
    platforms: [WidgetPlatformType.MobileWeb],
    display: WidgetDisplay.Block,
  },
  {
    widgetLib: 'antd-mobile',
    name: 'ProgressCircle',
    category: WidgetCategory.Feedback,
    platforms: [WidgetPlatformType.MobileWeb],
    display: WidgetDisplay.Block,
  },
  {
    widgetLib: 'antd-mobile',
    name: 'PullToRefresh',
    category: WidgetCategory.Feedback,
    platforms: [WidgetPlatformType.MobileWeb],
    display: WidgetDisplay.Block,
  },
  {
    widgetLib: 'antd-mobile',
    name: 'Result',
    category: WidgetCategory.Feedback,
    platforms: [WidgetPlatformType.MobileWeb],
    display: WidgetDisplay.Block,
  },
  {
    widgetLib: 'antd-mobile',
    name: 'Skeleton',
    category: WidgetCategory.Feedback,
    platforms: [WidgetPlatformType.MobileWeb],
    display: WidgetDisplay.Block,
  },
  {
    widgetLib: 'antd-mobile',
    name: 'SwipeAction',
    category: WidgetCategory.Feedback,
    platforms: [WidgetPlatformType.MobileWeb],
    display: WidgetDisplay.Block,
  },
  {
    widgetLib: 'antd-mobile',
    name: 'Toast',
    category: WidgetCategory.Feedback,
    platforms: [WidgetPlatformType.MobileWeb],
    display: WidgetDisplay.Block,
  },
  {
    widgetLib: 'antd-mobile',
    name: 'Badge',
    category: WidgetCategory.Other,
    platforms: [WidgetPlatformType.MobileWeb],
    display: WidgetDisplay.InlineBlock,
  },
  {
    widgetLib: 'antd-mobile',
    name: 'NoticeBar',
    category: WidgetCategory.Other,
    platforms: [WidgetPlatformType.MobileWeb],
    display: WidgetDisplay.Block,
  },
  {
    widgetLib: 'antd-mobile',
    name: 'ConfigProvider',
    category: WidgetCategory.Other,
    platforms: [WidgetPlatformType.MobileWeb],
    display: WidgetDisplay.Block,
  },
];
