import { WidgetCategory, WidgetPlatformType } from '@prisma/client';
import { WidgetData } from '../types';

export const antdMiniWidgetsData: WidgetData[] = [
  {
    widgetLib: 'antd-mini',
    name: 'Button',
    category: WidgetCategory.General,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mini',
    name: 'Icon',
    category: WidgetCategory.General,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mini',
    name: 'TabBar',
    category: WidgetCategory.Navigation,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mini',
    name: 'Tabs',
    category: WidgetCategory.Navigation,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mini',
    name: 'Avatar',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mini',
    name: 'Calendar',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mini',
    name: 'Collapse',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mini',
    name: 'Container',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mini',
    name: 'Divider',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mini',
    name: 'Empty',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mini',
    name: 'Grid',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mini',
    name: 'GuideTour',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mini',
    name: 'IndexBar',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mini',
    name: 'List',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mini',
    name: 'Progress',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mini',
    name: 'Steps',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mini',
    name: 'SwipeAction',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mini',
    name: 'Tag',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mini',
    name: 'Checkbox',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mini',
    name: 'Checklist',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mini',
    name: 'DatePicker',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mini',
    name: 'Form',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mini',
    name: 'ImageUpload',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mini',
    name: 'Input',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mini',
    name: 'NumberKeyboard',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mini',
    name: 'Picker',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mini',
    name: 'Radio',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mini',
    name: 'RareWordsKeyboard',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mini',
    name: 'Selector',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mini',
    name: 'Slider',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mini',
    name: 'Stepper',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mini',
    name: 'Switch',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mini',
    name: 'Badge',
    category: WidgetCategory.Feedback,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mini',
    name: 'NoticeBar',
    category: WidgetCategory.Feedback,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mini',
    name: 'ActionSheet',
    category: WidgetCategory.Feedback,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mini',
    name: 'Loading',
    category: WidgetCategory.Feedback,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mini',
    name: 'Modal',
    category: WidgetCategory.Feedback,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mini',
    name: 'Popover',
    category: WidgetCategory.Feedback,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mini',
    name: 'Popup',
    category: WidgetCategory.Feedback,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mini',
    name: 'Rate',
    category: WidgetCategory.Feedback,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mini',
    name: 'Result',
    category: WidgetCategory.Feedback,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mini',
    name: 'Skeleton',
    category: WidgetCategory.Feedback,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mini',
    name: 'Toast',
    category: WidgetCategory.Feedback,
    platforms: [WidgetPlatformType.MobileWeb],
  },
];
