import { WidgetCategory, WidgetPlatformType } from '@prisma/client';

type WidgetData = {
  name: string;
  widgetLib: string;
  category: WidgetCategory;
  platforms: WidgetPlatformType[];
  slots?: string[];
};

export const antdPcWidgetsData: WidgetData[] = [
  {
    widgetLib: 'antd',
    name: 'Button',
    category: WidgetCategory.General,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'FloatButton',
    category: WidgetCategory.General,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'Icon',
    category: WidgetCategory.General,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'Typography',
    category: WidgetCategory.General,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'Divider',
    category: WidgetCategory.Layout,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'Flex',
    category: WidgetCategory.Layout,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'Grid',
    category: WidgetCategory.Layout,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'Layout',
    category: WidgetCategory.Layout,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'Space',
    category: WidgetCategory.Layout,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'Anchor',
    category: WidgetCategory.Navigation,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'Breadcrumb',
    category: WidgetCategory.Navigation,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'Dropdown',
    category: WidgetCategory.Navigation,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'Menu',
    category: WidgetCategory.Navigation,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'Pagination',
    category: WidgetCategory.Navigation,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'Steps',
    category: WidgetCategory.Navigation,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'AutoComplete',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'Cascader',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'Checkbox',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'ColorPicker',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'DatePicker',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'Form',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'Input',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'InputNumber',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'Mentions',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'Radio',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'Rate',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'Select',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'Slider',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'Switch',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'TimePicker',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'Transfer',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'TreeSelect',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'Upload',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'Avatar',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'Badge',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'Calendar',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'Card',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'Carousel',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'Collapse',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'Descriptions',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'Empty',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'Image',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'List',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'Popover',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'QRCode',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'Segmented',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'Statistic',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'Table',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'Tabs',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'Tag',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'Timeline',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'Tooltip',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'Tour',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'Tree',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'Alert',
    category: WidgetCategory.Feedback,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'Drawer',
    category: WidgetCategory.Feedback,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'Message',
    category: WidgetCategory.Feedback,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'Modal',
    category: WidgetCategory.Feedback,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'Notification',
    category: WidgetCategory.Feedback,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'Popconfirm',
    category: WidgetCategory.Feedback,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'Progress',
    category: WidgetCategory.Feedback,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'Result',
    category: WidgetCategory.Feedback,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'Skeleton',
    category: WidgetCategory.Feedback,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'Spin',
    category: WidgetCategory.Feedback,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'Watermark',
    category: WidgetCategory.Feedback,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'Affix',
    category: WidgetCategory.Other,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'App',
    category: WidgetCategory.Other,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'ConfigProvider',
    category: WidgetCategory.Other,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'Util',
    category: WidgetCategory.Other,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'ProLayout',
    category: WidgetCategory.Heavyweight,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'ProForm',
    category: WidgetCategory.Heavyweight,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'ProTable',
    category: WidgetCategory.Heavyweight,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'ProDescriptions',
    category: WidgetCategory.Heavyweight,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'ProList',
    category: WidgetCategory.Heavyweight,
    platforms: [WidgetPlatformType.PcWeb],
  },
  {
    widgetLib: 'antd',
    name: 'EditableProTable',
    category: WidgetCategory.Heavyweight,
    platforms: [WidgetPlatformType.PcWeb],
  },
];

export const antdMobileWidgetsData: WidgetData[] = [
  {
    widgetLib: 'antd-mobile',
    name: 'AutoCenter',
    category: WidgetCategory.Layout,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mobile',
    name: 'SafeArea',
    category: WidgetCategory.Layout,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mobile',
    name: 'CapsuleTabs',
    category: WidgetCategory.Navigation,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mobile',
    name: 'IndexBar',
    category: WidgetCategory.Navigation,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mobile',
    name: 'JumboTabs',
    category: WidgetCategory.Navigation,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mobile',
    name: 'NavBar',
    category: WidgetCategory.Navigation,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mobile',
    name: 'SideBar',
    category: WidgetCategory.Navigation,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mobile',
    name: 'TabBar',
    category: WidgetCategory.Navigation,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mobile',
    name: 'Avatar',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mobile',
    name: 'Card',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mobile',
    name: 'Collapse',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mobile',
    name: 'Ellipsis',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mobile',
    name: 'FloatingPanel',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mobile',
    name: 'Image',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mobile',
    name: 'ImageViewer',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mobile',
    name: 'InfiniteScroll',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mobile',
    name: 'List',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mobile',
    name: 'PageIndicator',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mobile',
    name: 'Steps',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mobile',
    name: 'Swiper',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mobile',
    name: 'Tag',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mobile',
    name: 'WaterMark',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mobile',
    name: 'Footer',
    category: WidgetCategory.DataDisplay,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mobile',
    name: 'Cascader',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mobile',
    name: 'CascaderView',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mobile',
    name: 'CheckList',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mobile',
    name: 'Checkbox',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mobile',
    name: 'Form',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mobile',
    name: 'Input',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mobile',
    name: 'Picker',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mobile',
    name: 'PickerView',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mobile',
    name: 'Radio',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mobile',
    name: 'Rate',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mobile',
    name: 'SearchBar',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mobile',
    name: 'Selector',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mobile',
    name: 'Slider',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mobile',
    name: 'Stepper',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mobile',
    name: 'Switch',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mobile',
    name: 'TextArea',
    category: WidgetCategory.DataEntry,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mobile',
    name: 'ActionSheet',
    category: WidgetCategory.Feedback,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mobile',
    name: 'Dialog',
    category: WidgetCategory.Feedback,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mobile',
    name: 'Empty',
    category: WidgetCategory.Feedback,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mobile',
    name: 'ErrorBlock',
    category: WidgetCategory.Feedback,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mobile',
    name: 'Loading',
    category: WidgetCategory.Feedback,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mobile',
    name: 'Mask',
    category: WidgetCategory.Feedback,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mobile',
    name: 'Modal',
    category: WidgetCategory.Feedback,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mobile',
    name: 'Popover',
    category: WidgetCategory.Feedback,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mobile',
    name: 'Popup',
    category: WidgetCategory.Feedback,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mobile',
    name: 'ProgressBar',
    category: WidgetCategory.Feedback,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mobile',
    name: 'ProgressCircle',
    category: WidgetCategory.Feedback,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mobile',
    name: 'PullToRefresh',
    category: WidgetCategory.Feedback,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mobile',
    name: 'Result',
    category: WidgetCategory.Feedback,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mobile',
    name: 'Skeleton',
    category: WidgetCategory.Feedback,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mobile',
    name: 'SwipeAction',
    category: WidgetCategory.Feedback,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mobile',
    name: 'Toast',
    category: WidgetCategory.Feedback,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mobile',
    name: 'Badge',
    category: WidgetCategory.Other,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mobile',
    name: 'NoticeBar',
    category: WidgetCategory.Other,
    platforms: [WidgetPlatformType.MobileWeb],
  },
  {
    widgetLib: 'antd-mobile',
    name: 'ConfigProvider',
    category: WidgetCategory.Other,
    platforms: [WidgetPlatformType.MobileWeb],
  },
];
